name: CI
on: [push, pull_request]
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./linux/auto-setup.sh
        shell: bash
